max_connections = 5
connection_string = "postgres://postgres:postgres@localhost:5432/crates"
llm_malicious_score_threshold = 75
update_source_data = false
use_only_first_x_crates = 10
redis_url = "redis://localhost:6379"
max_crates_downloads = 0
insert_crates_in_chunks = 4000
